import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:go_router/go_router.dart';
import 'package:intl/intl.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:lucide_icons/lucide_icons.dart';
import 'package:share_plus/share_plus.dart';
import 'package:shop_keeper_project/core/theme/app_colors.dart';
import 'package:shop_keeper_project/core/widgets/glass_card.dart';
import 'package:shop_keeper_project/core/localization/app_strings.dart';
import 'package:shop_keeper_project/core/utils/barcode_generator_service.dart';
import 'package:shop_keeper_project/features/inventory/presentation/widgets/barcode_preview_card.dart';
import 'package:shop_keeper_project/features/inventory/domain/entities/product_entity.dart';
import 'package:shop_keeper_project/core/widgets/primary_button.dart';

class ProductDetailScreen extends StatelessWidget {
  final ProductEntity product;
  const ProductDetailScreen({super.key, required this.product});

  void _showBarcodeSheet(BuildContext context) {
    final barcodeService = BarcodeGeneratorService();
    final barcodeData = barcodeService.validateAndFixBarcode(product.barcode);

    if (barcodeData == null) {
      _showInfoSnackBar(context, 'NO BARCODE ASSIGNED', isError: true);
      return;
    }

    showModalBottomSheet(
      context: context,
      backgroundColor: Colors.transparent,
      isScrollControlled: true,
      builder: (ctx) => Container(
        padding: const EdgeInsets.symmetric(horizontal: 24),
        decoration: const BoxDecoration(
          color: AppColors.surface,
          borderRadius: BorderRadius.vertical(top: Radius.circular(32)),
          border: Border(top: BorderSide(color: AppColors.glassBorder)),
        ),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const SizedBox(height: 12),
            Container(width: 40, height: 4, decoration: BoxDecoration(color: AppColors.textMuted, borderRadius: BorderRadius.circular(2))),
            const SizedBox(height: 32),
            Row(
              children: [
                Icon(LucideIcons.qrCode, color: AppColors.primary, size: 24),
                const SizedBox(width: 16),
                Text(
                  'SECURITY ENCODING',
                  style: GoogleFonts.outfit(fontSize: 14, fontWeight: FontWeight.w900, color: AppColors.textPrimary, letterSpacing: 2),
                ),
              ],
            ),
            const SizedBox(height: 32),
            BarcodePreviewCard(
              barcodeData: barcodeData,
              productName: product.name,
              barcodeWidget: barcodeService.buildBarcodeWidget(
                data: barcodeData,
                type: BarcodeType.ean13,
                width: 280, height: 120,
              ),
            ),
            const SizedBox(height: 32),
            Row(
              children: [
                Expanded(
                  child: _buildQuickAction(LucideIcons.copy, 'COPY ID', () {
                    Clipboard.setData(ClipboardData(text: barcodeData));
                    Navigator.pop(ctx);
                    _showInfoSnackBar(context, 'ID COPIED TO VAULT');
                  }),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: _buildQuickAction(LucideIcons.share2, 'SHARE', () {
                    final text = '✨ LUXURY INVENTORY RECORD\n🛒 PRODUCT: ${product.name}\n📊 BARCODE: $barcodeData\n💰 VALUATION: ₹${product.sellPrice}\nGenerated by ShopKeeper PRO Executive Suite';
                    Share.share(text, subject: 'Product: ${product.name}');
                  }),
                ),
              ],
            ),
            const SizedBox(height: 48),
          ],
        ).animate().slideY(begin: 0.1, duration: 300.ms),
      ),
    );
  }

  void _showInfoSnackBar(BuildContext context, String message, {bool isError = false}) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message.toUpperCase(), style: GoogleFonts.outfit(fontWeight: FontWeight.w900, fontSize: 11, letterSpacing: 1, color: Colors.white)),
        backgroundColor: isError ? AppColors.error : AppColors.primary,
        behavior: SnackBarBehavior.floating,
        margin: const EdgeInsets.all(24),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
      ),
    );
  }

  Widget _buildQuickAction(IconData icon, String label, VoidCallback onTap) {
    return Container(
      decoration: BoxDecoration(
        color: AppColors.surface,
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: AppColors.glassBorder),
      ),
      child: Material(
        color: Colors.transparent,
        child: InkWell(
          onTap: onTap,
          borderRadius: BorderRadius.circular(20),
          child: Padding(
            padding: const EdgeInsets.symmetric(vertical: 16),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Icon(icon, color: AppColors.primary, size: 18),
                const SizedBox(width: 12),
                Text(label, style: GoogleFonts.outfit(fontSize: 11, fontWeight: FontWeight.w900, color: AppColors.textPrimary, letterSpacing: 1)),
              ],
            ),
          ),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final profit = product.sellPrice - product.buyPrice;
    final profitPercentage = product.buyPrice > 0 ? (profit / product.buyPrice) * 100 : 0.0;

    return Scaffold(
      backgroundColor: Colors.transparent,
      appBar: AppBar(
        title: Text(
          'ASSET INTELLIGENCE',
          style: GoogleFonts.outfit(fontWeight: FontWeight.w900, letterSpacing: 2, fontSize: 13),
        ),
        centerTitle: true,
        actions: [
          if (product.barcode != null && product.barcode!.isNotEmpty)
            IconButton(
              onPressed: () => _showBarcodeSheet(context),
              icon: Icon(LucideIcons.qrCode, color: AppColors.primary, size: 20),
            ),
        ],
      ),
      body: SingleChildScrollView(
        physics: const BouncingScrollPhysics(),
        padding: const EdgeInsets.all(24),
        child: Column(
          children: [
            GlassCard(
              padding: const EdgeInsets.all(32),
              backgroundOpacity: 0.05,
              child: Column(
                children: [
                  // Specimen Portal
                  Container(
                    width: 140, height: 140,
                    decoration: BoxDecoration(
                      color: AppColors.surface,
                      borderRadius: BorderRadius.circular(32),
                      border: Border.all(color: AppColors.glassBorder, width: 2),
                      boxShadow: [
                        BoxShadow(color: Colors.black.withOpacity(0.4), blurRadius: 40, offset: const Offset(0, 20))
                      ],
                    ),
                    child: Center(
                      child: product.imageUrl != null 
                          ? const Icon(LucideIcons.image, size: 48, color: AppColors.primary)
                          : const Icon(LucideIcons.package, size: 64, color: AppColors.primary),
                    ),
                  ),
                  const SizedBox(height: 32),
                  Text(
                    product.name.toUpperCase(),
                    style: GoogleFonts.outfit(fontSize: 22, fontWeight: FontWeight.w900, color: AppColors.textPrimary, letterSpacing: 1),
                    textAlign: TextAlign.center,
                  ),
                  const SizedBox(height: 8),
                  Container(
                    padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 6),
                    decoration: BoxDecoration(
                      color: AppColors.primary.withOpacity(0.05),
                      borderRadius: BorderRadius.circular(12),
                      border: Border.all(color: AppColors.primary.withOpacity(0.2)),
                    ),
                    child: Text(
                      product.category.toUpperCase(),
                      style: GoogleFonts.outfit(fontSize: 10, fontWeight: FontWeight.w900, color: AppColors.primary, letterSpacing: 2),
                    ),
                  ),
                  const SizedBox(height: 48),

                  // Data Matrix
                  _buildDataRow(LucideIcons.shoppingBag, 'ACQUISITION COST', '₹${NumberFormat('#,##0').format(product.buyPrice)}'),
                  _buildDataRow(LucideIcons.tag, 'RETAIL VALUATION', '₹${NumberFormat('#,##0').format(product.sellPrice)}', valueColor: AppColors.primary),
                  _buildDataRow(
                    LucideIcons.trendingUp, 
                    'NET MARGIN', 
                    '₹${NumberFormat('#,##0').format(profit)} (${profitPercentage.toStringAsFixed(1)}%)',
                    valueColor: profit >= 0 ? AppColors.success : AppColors.error,
                  ),
                  const Padding(padding: EdgeInsets.symmetric(vertical: 24), child: Divider(color: AppColors.glassBorder)),
                  _buildDataRow(
                    LucideIcons.layers, 
                    'INVENTORY LEVEL', 
                    '${product.stockQuantity} UNITS',
                    valueColor: product.stockQuantity <= product.minStockAlert ? AppColors.error : AppColors.textPrimary,
                    isPositive: product.stockQuantity > product.minStockAlert,
                  ),
                  _buildDataRow(LucideIcons.bell, 'ALERT THRESHOLD', '${product.minStockAlert} UNITS', valueColor: AppColors.error),
                ],
              ),
            ).animate().fadeIn(duration: 400.ms).slideY(begin: 0.05),

            const SizedBox(height: 32),

            // Primary Actions
            if (product.barcode != null && product.barcode!.isNotEmpty)
              PrimaryButton(
                text: 'GENERATE ASSET LABEL',
                onPressed: () => _showBarcodeSheet(context),
              ).animate().fadeIn(duration: 400.ms, delay: 200.ms),
            
            const SizedBox(height: 64),
          ],
        ),
      ),
    );
  }

  Widget _buildDataRow(IconData icon, String label, String value, {Color? valueColor, bool isPositive = false}) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 12),
      child: Row(
        children: [
          Icon(icon, size: 16, color: AppColors.textMuted),
          const SizedBox(width: 16),
          Expanded(
            child: Text(
              label,
              style: GoogleFonts.outfit(fontSize: 10, fontWeight: FontWeight.w900, color: AppColors.textMuted, letterSpacing: 1.5),
            ),
          ),
          Text(
            value,
            style: GoogleFonts.outfit(
              fontSize: 14, 
              fontWeight: FontWeight.w900, 
              color: valueColor ?? AppColors.textPrimary,
            ),
          ),
        ],
      ),
    );
  }
}
