// GENERATED BY FLUTTERFIRE DO NOT MODIFY.
// This file is automatically generated and any manual changes will be overwritten.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform: $defaultTargetPlatform',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5zwfYC7gNZDCUdyJ11qHWEgeYEgU-Ge8',
    appId: '1:660090449225:web:5e71f041559bf619fefe98',
    messagingSenderId: '660090449225',
    projectId: 'shopkeeper-9f594',
    authDomain: 'shopkeeper-9f594.firebaseapp.com',
    storageBucket: 'shopkeeper-9f594.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5zwfYC7gNZDCUdyJ11qHWEgeYEgU-Ge8',
    appId: '1:660090449225:android:5e71f041559bf619fefe98',
    messagingSenderId: '660090449225',
    projectId: 'shopkeeper-9f594',
    storageBucket: 'shopkeeper-9f594.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5zwfYC7gNZDCUdyJ11qHWEgeYEgU-Ge8',
    appId: '1:660090449225:ios:5e71f041559bf619fefe98',
    messagingSenderId: '660090449225',
    projectId: 'shopkeeper-9f594',
    storageBucket: 'shopkeeper-9f594.firebasestorage.app',
    iosBundleId: 'com.example.shopkeeper.shop_keeper_project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5zwfYC7gNZDCUdyJ11qHWEgeYEgU-Ge8',
    appId: '1:660090449225:windows:5e71f041559bf619fefe98',
    messagingSenderId: '660090449225',
    projectId: 'shopkeeper-9f594',
    authDomain: 'shopkeeper-9f594.firebaseapp.com',
    storageBucket: 'shopkeeper-9f594.firebasestorage.app',
  );
}
