// Centralized string repository

enum AppLanguage { english, hindi }

class AppStrings {
  static AppLanguage currentLanguage = AppLanguage.english;

  static String get(String key) {
    if (currentLanguage == AppLanguage.hindi) {
      return _hindi[key] ?? _english[key] ?? key;
    }
    return _english[key] ?? key;
  }

  static const Map<String, String> _english = {
    'app_name': 'ShopKeeper PRO',
    'inventory_hub': 'INVENTORY HUB',
    'search_products': 'Search products...',
    'new_product': 'NEW PRODUCT',
    'no_stock_items': 'NO STOCK ITEMS',
    'empty_inventory_message': 'Your inventory is currently empty.\nTap the + button to add products.',
    'quick_sale': 'Quick sale',
    'adjust_stock': 'ADJUST STOCK',
    'confirm_delete': 'Are you sure you want to delete this?',
    'delete_warning': 'This action cannot be undone.',
    'delete': 'DELETE',
    'cancel': 'CANCEL',
    'customers': 'CUSTOMERS',
    'search_customers': 'Search customers...',
    'new_customer': 'NEW CUSTOMER',
    'revenue': 'REVENUE',
    'profit': 'PROFIT',
    'expenses': 'EXPENSES',
    'net_profit': 'NET PROFIT',
    'control_center': 'CONTROL CENTER',
    'language': 'Language',
    'hindi': 'Hindi (हिंदी)',
    'english': 'English',
    'save': 'SAVE',
    'success': 'Success',
    'error': 'Error',
    'search_expenses': 'Search expenses...',
    'no_outflow_logged': 'NO OUTFLOW LOGGED',
    'no_outflow_message': 'You have not recorded any business expenses today.',
    'record_expense': 'RECORD EXPENSE',
    'expense_title': 'EXPENSE TITLE',
    'category': 'CATEGORY',
    'amount': 'AMOUNT',
    'save_record': 'SAVE RECORD',
    'expense_removed': 'Expense removed',
    'new_inventory_item': 'NEW INVENTORY ITEM',
    'capture_image': 'CAPTURE PRODUCT IMAGE',
    'import_gallery': 'IMPORT FROM GALLERY',
    'visual_specimen': 'VISUAL SPECIMEN',
    'upload_image_hint': 'Upload high-res product image',
    'core_specifications': 'CORE SPECIFICATIONS',
    'product_designation': 'PRODUCT DESIGNATION',
    'data_classification': 'DATA CLASSIFICATION',
    'acq_cost': 'ACQ COST',
    'retail_val': 'RETAIL VAL',
    'curr_stock': 'CURR STOCK',
    'alert_lvl': 'ALERT LVL',
    'barcode_encoding': 'BARCODE ENCODING',
    'commit_to_inventory': 'COMMIT TO INVENTORY',
    'item_logged': 'ITEM LOGGED TO DATABASE',
    'item_updated': 'ITEM UPDATED SUCCESSFULLY',
    'product_name_required': 'PRODUCT DESIGNATION REQUIRED',
    'barcode_acquisition': 'BARCODE ACQUISITION',
    'adjust_stock_hint': 'Manually update inventory count',
    'no_results': 'No products match your search',
    'no_customers_yet': 'No Customers Yet',
    'add_first_customer_message': 'Tap + to add your first customer',
    'try_different_search': 'Try a different search term',
    'financial_overview': 'FINANCIAL OVERVIEW',
    'smart_insights': 'SMART INSIGHTS',
    'ai_powered': 'AI POWERED',
    'revenue_trend': 'REVENUE TREND',
    'todays_revenue': 'TODAY\'S REVENUE',
    'todays_profit': 'TODAY\'S PROFIT',
    'monthly_revenue': 'MONTHLY REVENUE',
    'todays_expenses': 'TODAY\'S EXPENSES',
    'net_profit_summary': 'NET PROFIT',
    'stock_alerts': 'STOCK ALERTS',
    'restock_recommended': 'RESTOCK RECOMMENDED',
    'business_health': 'BUSINESS HEALTH',
    'pos_billing': 'BILLING',
    'customers_action': 'CUSTOMERS',
    'expenses_action': 'EXPENSES',
    'ai_scanner': 'AI SCANNER',
    'account_security': 'ACCOUNT & SECURITY',
    'business_profile': 'Business Profile',
    'manage_shop_details': 'Manage shop details and branding',
    'access_configuration': 'Access Configuration',
    'update_pin_hint': 'Update secure 4-digit terminal PIN',
    'preferences': 'PREFERENCES',
    'business_tools': 'BUSINESS TOOLS',
    'gst_tax_settings': 'GST & Tax Settings',
    'configure_tax_hint': 'Configure default tax rates for billing',
    'customer_ledger': 'Customer Ledger',
    'manage_udhar_hint': 'Manage Udhar credit and payments',
    'data_engine': 'DATA ENGINE',
    'cloud_sync': 'Cloud Synchronization',
    'sync_hint': 'Mirror local database to secure cloud',
    'clear_cache': 'Clear Local Cache',
    'clear_cache_hint': 'Remove temporary data (preserves records)',
    'labs_info': 'LABS & INFO',
    'system_intelligence': 'System Intelligence',
    'version_info': 'Version 2.0.0-PRO • Production build',
    'terminate_session': 'Terminate Session',
    'sign_out_hint': 'Securely sign out of terminal',
    'tax_configuration_title': 'TAX CONFIGURATION',
    'default_gst_label': 'Default GST Rate (%)',
    'save_config': 'SAVE CONFIG',
    'clear_cache_title': 'CLEAR CACHE',
    'clear_cache_message': 'This will clear temporary data only. Your sales, products, and customer records will not be affected.',
    'clear_action': 'CLEAR',
    'sign_out_title': 'TERMINATE SESSION',
    'sign_out_confirm': 'Are you sure you want to sign out? All offline data is preserved.',
    'edit_profile': 'EDIT PROFILE',
    'save_profile': 'SAVE PROFILE',
    'shop_identity': 'SHOP IDENTITY',
    'encrypted_business': 'ENCRYPTED BUSINESS',
    'operator_name': 'OPERATOR NAME',
    'terminal_id': 'SECURE TERMINAL ID',
    'recovery_data': 'RECOVERY DATA',
    'edit_config': 'EDIT CONFIG',
    'core_parameters': 'CORE PARAMETERS',
    'shop_designation': 'SHOP DESIGNATION',
    'terminal_link': 'TERMINAL LINK',
    'item_removed': 'ITEM REMOVED',
    'edit_product_action': 'EDIT PRODUCT',
    'edit_product_hint': 'Change product name, price or category',
    'quantity_change': 'QUANTITY CHANGE',
    'confirm_action': 'CONFIRM',
    'logout_success': 'LOGGED OUT SUCCESSFULLY',
    'no_matching_records': 'No matching records found',
    'rent_bills': 'Rent/Bills',
    'stock_purchase': 'Stock Purchase',
    'staff_salary': 'Staff Salary',
    'others': 'Others',
    'expense_hint': 'e.g. Electricity Bill',
    'customer_name': 'Customer Name',
    'phone_number': 'Phone Number',
    'notes_optional': 'Notes (optional)',
    'customer_required': 'Name and Phone are required',
    'total': 'TOTAL',
    'udhar': 'UDHAR',
    'active': 'ACTIVE',
    'settled': 'Settled',
    'general_store': 'General Store',
    'sweets_bakery': 'Sweets/Bakery',
    'biscuits_snacks': 'Biscuits/Snacks',
    'visual_theme': 'Visual Theme',
    'dark_mode_active': 'Godly Obsidian (Dark)',
    'light_mode_active': 'Royal Daylight (Light)',
    'discount': 'Discount',
    'apply_discount': 'Apply Discount',
    'transaction_verified': 'TRANSACTION VERIFIED',
    'credit_transaction': 'CREDIT TRANSACTION',
    'bill_to': 'BILL TO',
    'inventory_items': 'INVENTORY ITEMS',
    'base_amount': 'Base Amount',
    'confirm_print': 'CONFIRM & PRINT',
    'share': 'SHARE',
    'total_settled': 'TOTAL SETTLED',
    'total_on_credit': 'TOTAL ON CREDIT',
    'generate_pdf': 'Generate PDF',
    'view_invoice': 'View Invoice',
    'print_receipt': 'Print Receipt',
    'share_digital': 'Share Digital Copy',
  };

  static const Map<String, String> _hindi = {
    'app_name': 'शॉपकीपर प्रो',
    'inventory_hub': 'इन्वेंटरी हब',
    'search_products': 'उत्पाद खोजें...',
    'new_product': 'नया उत्पाद',
    'no_stock_items': 'कोई स्टॉक आइटम नहीं',
    'empty_inventory_message': 'आपकी इन्वेंट्री अभी खाली है।\nउत्पाद जोड़ने के लिए + बटन पर टैप करें।',
    'quick_sale': 'क्विक सेल',
    'adjust_stock': 'स्टॉक समायोजित करें',
    'confirm_delete': 'क्या आप वाकई इसे हटाना चाहते हैं?',
    'delete_warning': 'यह क्रिया पूर्ववत नहीं की जा सकती।',
    'delete': 'हटाएं',
    'cancel': 'रद्द करें',
    'customers': 'ग्राहक',
    'search_customers': 'ग्राहक खोजें...',
    'new_customer': 'नया ग्राहक',
    'revenue': 'राजस्व',
    'profit': 'लाभ',
    'expenses': 'खर्च',
    'net_profit': 'शुद्ध लाभ',
    'control_center': 'कंट्रोल सेंटर',
    'language': 'भाषा',
    'hindi': 'हिंदी',
    'english': 'अंग्रेज़ी',
    'save': 'सहेजें',
    'success': 'सफल',
    'error': 'त्रुटि',
    'search_expenses': 'खर्च खोजें...',
    'no_outflow_logged': 'कोई खर्च दर्ज नहीं',
    'no_outflow_message': 'आपने आज कोई व्यावसायिक खर्च दर्ज नहीं किया है।',
    'record_expense': 'खर्च दर्ज करें',
    'expense_title': 'खर्च का शीर्षक',
    'category': 'श्रेणी',
    'amount': 'रकम',
    'save_record': 'रिकॉर्ड सहेजें',
    'expense_removed': 'खर्च हटा दिया गया',
    'new_inventory_item': 'नया इन्वेंट्री आइटम',
    'capture_image': 'उत्पाद की छवि लें',
    'import_gallery': 'गैलरी से चुनें',
    'visual_specimen': 'दृश्य नमूना',
    'upload_image_hint': 'उत्पाद की स्पष्ट छवि अपलोड करें',
    'core_specifications': 'मुख्य विनिर्देश',
    'product_designation': 'उत्पाद का नाम',
    'data_classification': 'डेटा वर्गीकरण',
    'acq_cost': 'खरीद लागत',
    'retail_val': 'खुदरा मूल्य',
    'curr_stock': 'वर्तमान स्टॉक',
    'alert_lvl': 'अलर्ट स्तर',
    'barcode_encoding': 'बारकोड एन्कोडिंग',
    'commit_to_inventory': 'इन्वेंट्री में जोड़ें',
    'item_logged': 'आइटम डेटाबेस में जोड़ा गया',
    'item_updated': 'आइटम सफलतापूर्वक अपडेट किया गया',
    'product_name_required': 'उत्पाद का नाम आवश्यक है',
    'barcode_acquisition': 'बारकोड स्कैन',
    'adjust_stock_hint': 'स्टॉक की संख्या मैन्युअल रूप से बदलें',
    'no_results': 'आपके खोज के अनुसार कोई उत्पाद नहीं मिला',
    'no_customers_yet': 'अभी तक कोई ग्राहक नहीं है',
    'add_first_customer_message': 'पहला ग्राहक जोड़ने के लिए + पर टैप करें',
    'try_different_search': 'किसी अन्य खोज शब्द का प्रयास करें',
    'financial_overview': 'वित्तीय अवलोकन',
    'smart_insights': 'स्मार्ट जानकारी',
    'ai_powered': 'एआई संचालित',
    'revenue_trend': 'राजस्व का रुझान',
    'todays_revenue': 'आज का राजस्व',
    'todays_profit': 'आज का लाभ',
    'monthly_revenue': 'मासिक राजस्व',
    'todays_expenses': 'आज के खर्च',
    'net_profit_summary': 'शुद्ध लाभ',
    'stock_alerts': 'स्टॉक अलर्ट',
    'restock_recommended': 'रीस्टॉक की सिफारिश',
    'business_health': 'व्यवसाय की स्थिति',
    'pos_billing': 'बिलिंग',
    'customers_action': 'ग्राहक',
    'expenses_action': 'खर्च',
    'ai_scanner': 'एआई स्कैनर',
    'account_security': 'खाता और सुरक्षा',
    'business_profile': 'व्यावसायिक प्रोफ़ाइल',
    'manage_shop_details': 'विवरण और ब्रांडिंग प्रबंधित करें',
    'access_configuration': 'एक्सेस कॉन्फ़िगरेशन',
    'update_pin_hint': 'सुरक्षित टर्मिनल पिन बदलें',
    'preferences': 'वरियताएँ',
    'business_tools': 'व्यावसायिक उपकरण',
    'gst_tax_settings': 'GST और टैक्स सेटिंग',
    'configure_tax_hint': 'बिलिंग के लिए टैक्स दरें सेट करें',
    'customer_ledger': 'ग्राहक लेजर',
    'manage_udhar_hint': 'उधार और भुगतान प्रबंधित करें',
    'data_engine': 'डेटा इंजन',
    'cloud_sync': 'क्लाउड सिंक्रनाइज़ेशन',
    'sync_hint': 'डेटाबेस को सुरक्षित क्लाउड पर सिंक करें',
    'clear_cache': 'कैश साफ़ करें',
    'clear_cache_hint': 'अस्थायी डेटा हटाएँ (रिकॉर्ड सुरक्षित हैं)',
    'labs_info': 'लैब्स और जानकारी',
    'system_intelligence': 'सिस्टम इंटेलिजेंस',
    'version_info': 'संस्करण 2.0.0-PRO • प्रोडक्शन बिल्ड',
    'terminate_session': 'सेशन समाप्त करें',
    'sign_out_hint': 'टर्मिनल से सुरक्षित रूप से साइन आउट करें',
    'tax_configuration_title': 'टैक्स कॉन्फ़िगरेशन',
    'default_gst_label': 'डिफ़ॉल्ट GST दर (%)',
    'save_config': 'कॉन्फ़िगरेशन सहेजें',
    'clear_cache_title': 'कैश साफ़ करें',
    'clear_cache_message': 'यह केवल अस्थायी डेटा को साफ़ करेगा। आपके रिकॉर्ड सुरक्षित रहेंगे।',
    'clear_action': 'साफ़ करें',
    'sign_out_title': 'सेशन समाप्त करें',
    'sign_out_confirm': 'क्या आप वाकई साइन आउट करना चाहते हैं?',
    'edit_profile': 'प्रोफ़ाइल बदलें',
    'save_profile': 'प्रोफ़ाइल सहेजें',
    'shop_identity': 'दुकान की पहचान',
    'encrypted_business': 'सुरक्षित व्यवसाय',
    'operator_name': 'संचालक का नाम',
    'terminal_id': 'सुरक्षित टर्मिनल आईडी',
    'recovery_data': 'रिकवरी डेटा',
    'edit_config': 'कॉन्फ़िगरेशन बदलें',
    'core_parameters': 'मुख्य पैरामीटर',
    'shop_designation': 'दुकान का नाम',
    'terminal_link': 'टर्मिनल लिंक',
    'item_removed': 'आइटम हटा दिया गया',
    'edit_product_action': 'उत्पाद बदलें',
    'edit_product_hint': 'नाम, मूल्य या श्रेणी बदलें',
    'quantity_change': 'मात्रा बदलें',
    'confirm_action': 'पुष्टि करें',
    'logout_success': 'सफलतापूर्वक लॉग आउट किया गया',
    'no_matching_records': 'कोई मेल खाने वाला रिकॉर्ड नहीं मिला',
    'rent_bills': 'किराया/बिल',
    'stock_purchase': 'स्टॉक खरीद',
    'staff_salary': 'कर्मचारी वेतन',
    'others': 'अन्य',
    'expense_hint': 'जैसे- बिजली बिल',
    'customer_name': 'ग्राहक का नाम',
    'phone_number': 'फ़ोन नंबर',
    'notes_optional': 'नोट्स (वैकल्पिक)',
    'customer_required': 'नाम और फोन आवश्यक हैं',
    'total': 'कुल',
    'udhar': 'उधार',
    'active': 'सक्रिय',
    'settled': 'चुकाया गया',
    'general_store': 'जनरल स्टोर',
    'sweets_bakery': 'मिठाई/बेकरी',
    'biscuits_snacks': 'बिस्कुट/स्नैक्स',
    'visual_theme': 'विज़ुअल थीम',
    'dark_mode_active': 'गॉडली ओब्सीडियन (डार्क)',
    'light_mode_active': 'रॉयल डेलाइट (लाइट)',
    'discount': 'छूट',
    'apply_discount': 'छूट लागू करें',
    'transaction_verified': 'लेन-देन सत्यापित',
    'credit_transaction': 'क्रेडिट ट्रांजैक्शन',
    'bill_to': 'बिल प्राप्तकर्ता',
    'inventory_items': 'इन्वेंट्री आइटम',
    'base_amount': 'मूल राशि',
    'confirm_print': 'पुष्टि करें और प्रिंट लें',
    'share': 'शेयर करें',
    'total_settled': 'कुल भुगतान',
    'total_on_credit': 'कुल उधार',
    'generate_pdf': 'PDF बनाएं',
    'view_invoice': 'इनवॉइस देखें',
    'print_receipt': 'रसीद प्रिंट करें',
    'share_digital': 'डिजिटल कॉपी शेयर करें',
  };
}
