import 'package:hive_flutter/hive_flutter.dart';
import 'package:share_plus/share_plus.dart';
import 'package:intl/intl.dart';

/// Backup & Restore service for shop data
class BackupService {
  /// Generate a text-based backup report of all records
  static Future<String> generateBackupReport({
    required Box productBox,
    required Box saleBox,
    required Box expenseBox,
    required Box customerBox,
  }) async {
    final buffer = StringBuffer();
    final now = DateTime.now();
    buffer.writeln('═══════════════════════════════════');
    buffer.writeln('  SHOPKEEPER PRO — DATA BACKUP');
    buffer.writeln('  ${DateFormat('dd MMM yyyy, hh:mm a').format(now)}');
    buffer.writeln('═══════════════════════════════════');
    buffer.writeln('');

    // Products summary
    buffer.writeln('📦 PRODUCTS: ${productBox.length} records');
    buffer.writeln('────────────────────────────────────');
    for (final item in productBox.values) {
      buffer.writeln('  ${item.name} | ₹${item.sellPrice} | Stock: ${item.stockQuantity}');
    }
    buffer.writeln('');

    // Sales summary
    buffer.writeln('🧾 SALES: ${saleBox.length} records');
    buffer.writeln('────────────────────────────────────');
    double totalRevenue = 0;
    for (final item in saleBox.values) {
      totalRevenue += item.totalAmount;
    }
    buffer.writeln('  Total Revenue: ₹${totalRevenue.toStringAsFixed(2)}');
    buffer.writeln('');

    // Expenses summary
    buffer.writeln('💰 EXPENSES: ${expenseBox.length} records');
    buffer.writeln('────────────────────────────────────');
    double totalExpenses = 0;
    for (final item in expenseBox.values) {
      totalExpenses += item.amount;
    }
    buffer.writeln('  Total Expenses: ₹${totalExpenses.toStringAsFixed(2)}');
    buffer.writeln('');

    // Customers summary
    buffer.writeln('👥 CUSTOMERS: ${customerBox.length} records');
    buffer.writeln('────────────────────────────────────');
    for (final item in customerBox.values) {
      buffer.writeln('  ${item.name} | ${item.phone} | Balance: ₹${item.balance}');
    }
    buffer.writeln('');
    buffer.writeln('═══════════════════════════════════');
    buffer.writeln('  Backup Generated by ShopKeeper PRO');
    buffer.writeln('═══════════════════════════════════');

    return buffer.toString();
  }

  /// Share backup via share_plus
  static Future<void> shareBackup({
    required Box productBox,
    required Box saleBox,
    required Box expenseBox,
    required Box customerBox,
  }) async {
    final report = await generateBackupReport(
      productBox: productBox,
      saleBox: saleBox,
      expenseBox: expenseBox,
      customerBox: customerBox,
    );
    Share.share(report, subject: 'ShopKeeper PRO Backup — ${DateFormat('dd MMM yyyy').format(DateTime.now())}');
  }
}
